### ISSUE TITLE
Can Gephi do a partial load or lazy load or filter from db?

### ISSUE THREAD

**Issue by amalagaura** [datablend/gephi-blueprints-plugin#2]
If we have a very large graph, is there a way to use a blueprints graph as a backend and only see filtered information without loading the entire graph?

**Comment by TimmyStorms** [comment]
For now, there's no way to filter data before the import. You can use Gephi's filtering feature to filter after the import, but that might not be an option for you.

Feel free to send a PR that enables easy filtering.
